### ISSUE TITLE
Using right mouse click in trackmode leads to freeze

### ISSUE THREAD

**Issue by lukasepple** [grindhold/rainbow-lollipop#59]
pretty strange, unable to access context menu to delete branches currently.

**Comment by grindhold** [comment]
any further instructions on how to reproduce? i can't trigger this bug.

**Comment by lukasepple** [comment]
I restored my session several times before. Then I just opened trackmode
and right-mouse-clicked a node. Freeze.

**Comment by grindhold** [comment]
this happens only on arch apparently. as i don't have  any arch machine, further help or info would be very appreciated

**Comment by tilpner** [comment]
I was able to reproduce this, on Arch with dwm.

It froze dwm, and I got a backtrace of it from TTY:

    sudo gdb --pid=12771 --batch -ex 'bt'

```
[New LWP 12938]
[New LWP 12861]
[New LWP 12860]
[New LWP 12793]
[New LWP 12792]
[New LWP 12789]
[New LWP 12788]
[New LWP 12787]
[New LWP 12786]
[New LWP 12777]
[New LWP 12776]
[New LWP 12775]
[New LWP 12774]
[New LWP 12773]
[New LWP 12772]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
0x00007fb5ae9d8939 in syscall () from /usr/lib/libc.so.6
#0  0x00007fb5ae9d8939 in syscall () from /usr/lib/libc.so.6
#1  0x00007fb5b7c0fa3c in ?? () from /usr/lib/libglib-2.0.so.0
#2  0x00007fb5b5605b84 in clutter_gdk_handle_event () from /usr/lib/libclutter-1.0.so.0
#3  0x00007fb5b28a231c in ?? () from /usr/lib/libclutter-gtk-1.0.so.0
#4  0x00007fb5b719a419 in ?? () from /usr/lib/libgtk-3.so.0
#5  0x00007fb5b592d524 in ?? () from /usr/lib/libgobject-2.0.so.0
#6  0x00007fb5b5946a40 in g_signal_emit_valist () from /usr/lib/libgobject-2.0.so.0
#7  0x00007fb5b59478ef in g_signal_emit () from /usr/lib/libgobject-2.0.so.0
#8  0x00007fb5b72d3160 in ?? () from /usr/lib/libgtk-3.so.0
#9  0x00007fb5b72d3403 in ?? () from /usr/lib/libgtk-3.so.0
#10 0x00007fb5b72d6e6b in ?? () from /usr/lib/libgtk-3.so.0
#11 0x00007fb5b7197ba4 in ?? () from /usr/lib/libgtk-3.so.0
#12 0x00007fb5b7197e59 in ?? () from /usr/lib/libgtk-3.so.0
#13 0x00007fb5b72e78c9 in ?? () from /usr/lib/libgtk-3.so.0
#14 0x00007fb5b7197e24 in ?? () from /usr/lib/libgtk-3.so.0
#15 0x00007fb5b7197f7b in ?? () from /usr/lib/libgtk-3.so.0
#16 0x00007fb5b71ad767 in gtk_menu_popup_for_device () from /usr/lib/libgtk-3.so.0
#17 0x00007fb5b71adb5a in gtk_menu_popup () from /usr/lib/libgtk-3.so.0
#18 0x0000000000432b02 in rainbow_lollipop_node_do_clicked ()
#19 0x000000000043eb1c in rainbow_lollipop_site_node_do_clicked ()
#20 0x000000000043a46b in _rainbow_lollipop_site_node_do_clicked_clutter_click_action_clicked ()
#21 0x00007fb5b5930597 in g_cclosure_marshal_VOID__OBJECTv () from /usr/lib/libgobject-2.0.so.0
#22 0x00007fb5b592d524 in ?? () from /usr/lib/libgobject-2.0.so.0
#23 0x00007fb5b5946f97 in g_signal_emit_valist () from /usr/lib/libgobject-2.0.so.0
#24 0x00007fb5b59478ef in g_signal_emit () from /usr/lib/libgobject-2.0.so.0
#25 0x00007fb5b56389dc in ?? () from /usr/lib/libclutter-1.0.so.0
#26 0x00007fb5b56b3fdf in ?? () from /usr/lib/libclutter-1.0.so.0
#27 0x00007fb5b592d2f5 in g_closure_invoke () from /usr/lib/libgobject-2.0.so.0
#28 0x00007fb5b593f332 in ?? () from /usr/lib/libgobject-2.0.so.0
#29 0x00007fb5b5947195 in g_signal_emit_valist () from /usr/lib/libgobject-2.0.so.0
#30 0x00007fb5b59478ef in g_signal_emit () from /usr/lib/libgobject-2.0.so.0
#31 0x00007fb5b5617220 in clutter_actor_event () from /usr/lib/libclutter-1.0.so.0
#32 0x00007fb5b561ce61 in ?? () from /usr/lib/libclutter-1.0.so.0
#33 0x00007fb5b56559f9 in ?? () from /usr/lib/libclutter-1.0.so.0
#34 0x00007fb5b5656d5a in ?? () from /usr/lib/libclutter-1.0.so.0
#35 0x00007fb5b5671349 in ?? () from /usr/lib/libclutter-1.0.so.0
#36 0x00007fb5b56068db in ?? () from /usr/lib/libclutter-1.0.so.0
#37 0x00007fb5b592d524 in ?? () from /usr/lib/libgobject-2.0.so.0
#38 0x00007fb5b5946f97 in g_signal_emit_valist () from /usr/lib/libgobject-2.0.so.0
#39 0x00007fb5b5947e3a in g_signal_emit_by_name () from /usr/lib/libgobject-2.0.so.0
#40 0x00007fb5b6cfe38c in ?? () from /usr/lib/libgdk-3.so.0
#41 0x00007fb5b6cedcc8 in ?? () from /usr/lib/libgdk-3.so.0
#42 0x00007fb5b7bcc3a3 in ?? () from /usr/lib/libglib-2.0.so.0
#43 0x00007fb5b7bcb90d in g_main_context_dispatch () from /usr/lib/libglib-2.0.so.0
#44 0x00007fb5b7bcbce0 in ?? () from /usr/lib/libglib-2.0.so.0
#45 0x00007fb5b7bcc002 in g_main_loop_run () from /usr/lib/libglib-2.0.so.0
#46 0x00007fb5b7198825 in gtk_main () from /usr/lib/libgtk-3.so.0
#47 0x000000000041dd43 in rainbow_lollipop_application_real_command_line ()
#48 0x00007fb5ab7fb1f0 in ffi_call_unix64 () from /usr/lib/libffi.so.6
#49 0x00007fb5ab7fac58 in ffi_call () from /usr/lib/libffi.so.6
#50 0x00007fb5b592df5c in g_cclosure_marshal_generic_va () from /usr/lib/libgobject-2.0.so.0
#51 0x00007fb5b592d524 in ?? () from /usr/lib/libgobject-2.0.so.0
#52 0x00007fb5b5946a40 in g_signal_emit_valist () from /usr/lib/libgobject-2.0.so.0
#53 0x00007fb5b59478ef in g_signal_emit () from /usr/lib/libgobject-2.0.so.0
#54 0x00007fb5b5c152d3 in ?? () from /usr/lib/libgio-2.0.so.0
#55 0x00007fb5b5c1721d in ?? () from /usr/lib/libgio-2.0.so.0
#56 0x00007fb5b5c173e2 in g_application_run () from /usr/lib/libgio-2.0.so.0
#57 0x00000000004221fd in rainbow_lollipop_application_main ()
#58 0x000000000042224e in main ()
```

**Comment by grindhold** [comment]
the bug depends on a specific version of clutter. will enter the version numbers when i found out.

**Comment by lukasepple** [comment]
Or we simply play the clutter waiting game again.

**Comment by grindhold** [comment]
we can only count on them fixing the bug if there is another known application that triggers the bug. bonus points if said application is kind of relevant. but i'm afraid this time, we have to do it ourselves.

**Comment by grindhold** [comment]
once again, there's news on this topic:
1. I debugged through the whole stack yesterday and rainbow-lollipop seems to be triggering a rare bug in X (the function XIGrabDevice in libXi to be precise). Here the library will send a request to the Xserver and wait indefinitely for a response instead of returning an error code. I've talked to some folks in #xorg-devel. Turns out that this bug has been fixed in http://cgit.freedesktop.org/xorg/lib/libXi/commit/?id=c648441036cf5ffc5225cd484e2c906d374f0a4b . I hope that it solves our problem (or at least fixes it to a point where we get a valid X error message that crashes only the program and not anything else inside the desktop manager). From this point on, proper debugging will be easier.

**Comment by grindhold** [comment]
as @Profpatsch pointed out to me, I forgot to mention here that the Xinput-fix arrived but did not solve the problem at all, which is pretty annoying.  The bug is not fixed. I repeat: This bug is **not** fixed. If you know the Gtk/Clutter/GLib-stack, you'd do the project a huge favor if you could debug into it.

Further information: The problem does not happen in Debian jessie but happens on Debian stretch. This means that at some point inbetween something must have changed that triggers this bug.
